server:
  port: 9999

eureka:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #服务注册的地址
  instance:
    instance-id: elasticserch-service:9300
    prefer-ip-address: true

spring:
  application:
    name: elasticeserch-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300 #9200是图形界面端,9300代码端